<a href="https://colab.research.google.com/github/FFI-Vietnam/camtrap-tools/blob/main/04_create-decision-tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
This script evaluates recall accuracy of MegaDetector from a ground-truth dataset
and a result json file. Then it creates a set of visualization of recall values 
on each group of species.

After runnning this script, a 'results' folder is created

results
    |__ 
    
"""

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import json
import requests
import os
from tqdm.notebook import tqdm

from sklearn import tree
import graphviz

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# specifies Colab directories and file names
root = '/content/drive/'

dataset_folder = 'My Drive/FFI/MegaDetector Test/confusion-matrix/dataset'
contain_folder = 'My Drive/FFI/MegaDetector Test/confusion-matrix/data cleaning'
image_folder = 'My Drive/FFI/MegaDetector Test/confusion-matrix/visualization'

ground_truth_file_name = '01_ground-truth-table_Kon-Plong.csv'
taxon_match_table_file_name = '02_taxon-database-with-conservation-status.csv'
confusion_matrix_file_name = '03_confusion-matrix.csv'

In [4]:
# read and save file functions
def read_csv_Google_drive(root, contain_folder, file_name):
  file_path = os.path.join(root, contain_folder, file_name)
  return pd.read_csv(file_path)

def save_csv_Google_drive(df, root, contain_folder, file_name, index=False):
  """
  function to save a csv file to Google Drive
  param examples:
    root = '/content/drive/'
    contain_folder = 'My Drive/FFI/dataset'
    file_name = 'image_metadata(2020-06-26)_full.csv'
  """
  # save file to Colab runtime storage (will be deleted when this notebook is closed)
  df.to_csv('dataframe.csv', index=index)

  # save file back to Google Drive for permanent storage
  folder_path = os.path.join(root, contain_folder)
  file_path = os.path.join(root, contain_folder, file_name)
  try:
    os.makedirs(folder_path)
  except:
    pass

  with open('dataframe.csv', 'r') as f:
    df_file = f.read()

  with open(file_path, 'w') as f:
    f.write(df_file)

  print(f'File is saved to {file_name} in Google Drive at {file_path}')

def save_image_Google_drive(plt, root, contain_folder, file_name):
  """
  function to save an image file to Google Drive
  param examples:
    root = '/content/drive/'
    contain_folder = 'My Drive/FFI/dataset'
    file_name = 'MD_recall_all-species.jpg'
  """

  # save file back to Google Drive for permanent storage
  folder_path = os.path.join(root, contain_folder)
  file_path = os.path.join(root, contain_folder, file_name)
  try:
    os.makedirs(folder_path)
  except:
    pass

  plt.savefig(file_path)
  
  print(f'File is saved to {file_name} in Google Drive at {file_path}')

In [11]:
taxon_match_table = read_csv_Google_drive(root, contain_folder, taxon_match_table_file_name)
taxon_match_table

          id     class  ...           FFI_species_name    conservation_status
0    2002045  Mammalia  ...                      Human          Least Concern
1    2002596  Mammalia  ...     Yellow-throated Marten          Least Concern
2    2012904      Aves  ...     Yellow-breasted Magpie          Least Concern
3    2021113      Aves  ...                       Bird         Not Applicable
4    2003794  Mammalia  ...          Masked Palm Civet          Least Concern
..       ...       ...  ...                        ...                    ...
132  2015400      Aves  ...    Snowy-browed Flycatcher          Least Concern
133  2004518  Mammalia  ...   Grey-shanked Douc Langur  Critically Endangered
134  2015334      Aves  ...        Siberian Rubythroat          Least Concern
135  2015253      Aves  ...  Tickell's Blue Flycatcher          Least Concern
136  2021556       NaN  ...                      Blank         Not Applicable

[137 rows x 12 columns]

In [31]:
dat = read_csv_Google_drive(root, contain_folder, confusion_matrix_file_name)

# unspecified species
unspecified_species = ['Banded Krait', 
                       'Black-throated Laughingthrush',
                       'Impressed Tortoise',
                       'Small Asian Mongoose',
                       'All']


# change and drop columns
dat['FFI_species_name'] = dat['Unnamed: 0']
dat = dat[['FFI_species_name', 'Recall']]

# drop rows
dat = dat[~ dat['FFI_species_name'].isin(unspecified_species)]

# get labels
labs = dat['Recall']
labs = labs>0.7

# add conservation status
conservation_status = []
for species in dat['FFI_species_name']:
  conservation_status.append(taxon_match_table[taxon_match_table['FFI_species_name'] == species]['conservation_status'].iat[0])
dat['conservation_status'] = conservation_status

# add class
taxon_class = []
for species in dat['FFI_species_name']:
  taxon_class.append(taxon_match_table[taxon_match_table['FFI_species_name'] == species]['class'].iat[0])
dat['class'] = taxon_class

# add order
taxon_order = []
for species in dat['FFI_species_name']:
  taxon_order.append(taxon_match_table[taxon_match_table['FFI_species_name'] == species]['order'].iat[0])
dat['order'] = taxon_order

# fill na
dat.fillna(value={'order':'Hello'}, inplace=True)

# drop columns
dat.drop(columns=['FFI_species_name', 'Recall'], inplace=True)

# get dummies
dat = pd.get_dummies(dat, columns=['conservation_status', 'class', 'order'])

dat

     conservation_status_Critically Endangered  ...  order_Strigiformes
0                                            0  ...                   0
1                                            0  ...                   0
2                                            0  ...                   1
3                                            0  ...                   0
4                                            0  ...                   0
..                                         ...  ...                 ...
127                                          0  ...                   0
128                                          0  ...                   0
129                                          0  ...                   0
130                                          0  ...                   0
131                                          0  ...                   0

[128 rows x 30 columns]

In [32]:
# create model
clf = tree.DecisionTreeClassifier(max_leaf_nodes = 3)	
clf = clf.fit(dat, labs)

In [52]:
# calculate accuracy
correct = 0						
for i in range(len(dat)):	
    if clf.predict([dat.iloc[i]]) == labs.iloc[i]: 
      correct = correct + 1
100.0* correct / len(dat)

62.5

In [35]:
# visualize decision tree
dot_data = tree.export_graphviz(clf, feature_names=dat.columns,
                      filled=True, rounded=True) 
graph = graphviz.Source(dot_data)	
graph